global:
  scrape_interval: 15s

scrape_configs:
  # User-Service
  - job_name: 'wealist-user'
    metrics_path: '/actuator/prometheus'
    static_configs:
    ## dns 접근으로 나중에 변경
      - targets: ['host.docker.internal:8080']
    scrape_interval: 10s

  - job_name: 'wealist-board'
    static_configs:
      - targets: ['board-service:8000']
    metrics_path: /metrics
    scrape_interval: 5s
    
  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    
  # PostgreSQL 
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    
  # Prometheus 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']